class_name NerveSystem
extends Node
## Aggregates stimulation events from all body parts on an NPC.
## Processes touch input into comfort/discomfort deltas and forwards
## them to the CharacterProfile.
##
## Attach as a child of the NPC root that owns the ragdoll.

signal stimulation_event(part_name: String, touch_type: TouchType,
	intensity: float, comfort_delta: float, discomfort_delta: float)

## Touch interaction types generated by the player's hand system or mouth system.
enum TouchType {
	GRAB,          ## Held by the player
	RELEASE,       ## Just released
	PUSH,          ## Firm shove (double-click)
	PUSH_RELEASE,  ## Shove + release in one motion
	STROKE,        ## Gentle surface drag
	PULL,          ## Directional drag while held
	PRESS,         ## Sustained pressure (e.g., lean against)
	IMPACT,        ## Velocity-based collision (auto-detected by BodyPart)
	LICK,          ## Tongue surface contact (wet, warm, light pressure)
	SUCK,          ## Oral negative-pressure envelope (rhythmic pull)
	BITE,          ## Jaw clamp (pressure scales with jaw closure)
}

## Per-part runtime stimulation accumulator.
var _stimulation: Dictionary = {}  # part_name → float
## Per-part sensitivity lookup (assigned at build time).
var _sensitivity_map: Dictionary = {}  # part_name → NerveSensitivity

## Reference to this NPC's character profile (found at runtime or set externally).
var _profile: CharacterProfile = null


func _ready() -> void:
	# Try to find a sibling CharacterProfile
	for sibling: Node in get_parent().get_children():
		if sibling is CharacterProfile:
			_profile = sibling as CharacterProfile
			break


func _physics_process(delta: float) -> void:
	# Decay stimulation over time
	for part_name: String in _stimulation.keys():
		var current: float = _stimulation[part_name] as float
		if current <= 0.0:
			continue
		var decay: float = 0.5  # default
		if _sensitivity_map.has(part_name):
			decay = (_sensitivity_map[part_name] as NerveSensitivity).stimulation_decay
		_stimulation[part_name] = maxf(current - decay * delta, 0.0)


## Register a body part's sensitivity (called by ragdoll builder or body_part).
func register_part(part_name: String, sensitivity: NerveSensitivity) -> void:
	_sensitivity_map[part_name] = sensitivity
	_stimulation[part_name] = 0.0


## Set the entire sensitivity map at once.
func set_sensitivity_map(sensitivity_map: Dictionary) -> void:
	_sensitivity_map = sensitivity_map
	for part_name: String in sensitivity_map.keys():
		if not _stimulation.has(part_name):
			_stimulation[part_name] = 0.0


## Process a touch event on a body part. This is the main entry point.
func receive_touch(part_name: String, touch_type: TouchType,
		raw_intensity: float = 1.0) -> void:
	if not _sensitivity_map.has(part_name):
		# Unknown part — register with default neutral sensitivity
		_sensitivity_map[part_name] = NerveSensitivity.create(
			0.3, NerveSensitivity.Zone.NEUTRAL, 0.2, 0.1)
		_stimulation[part_name] = 0.0

	var sens: NerveSensitivity = _sensitivity_map[part_name] as NerveSensitivity
	var intensity: float = raw_intensity * sens.base_sensitivity

	# Scale by touch type
	var type_mult: float = _get_touch_multiplier(touch_type, sens.zone_type)
	intensity *= type_mult

	# Accumulate stimulation
	_stimulation[part_name] = minf(
		(_stimulation[part_name] as float) + intensity, 100.0)

	# Compute comfort/discomfort deltas
	var comfort_delta: float = intensity * sens.comfort_weight
	var discomfort_delta: float = intensity * sens.discomfort_weight

	# Zone-specific adjustments
	match sens.zone_type:
		NerveSensitivity.Zone.EROGENOUS:
			comfort_delta *= 1.5
		NerveSensitivity.Zone.PAIN_PRONE:
			discomfort_delta *= 1.8
			comfort_delta *= 0.5
		NerveSensitivity.Zone.TICKLISH:
			# Ticklish = mix of comfort and discomfort
			comfort_delta *= 1.2
			discomfort_delta *= 1.1
		NerveSensitivity.Zone.PRESSURE_POINT:
			# Deep pressure can feel good at low intensity, painful at high
			if raw_intensity > 0.6:
				discomfort_delta *= 1.5
			else:
				comfort_delta *= 1.4
				discomfort_delta *= 0.3

	# Push comfort/discomfort to profile
	if _profile != null:
		_profile.add_comfort(comfort_delta)
		_profile.add_discomfort(discomfort_delta)

	stimulation_event.emit(part_name, touch_type, intensity,
		comfort_delta, discomfort_delta)


## Get current stimulation level for a specific part (0–100).
func get_stimulation(part_name: String) -> float:
	if _stimulation.has(part_name):
		return _stimulation[part_name] as float
	return 0.0


## Get total stimulation across all parts.
func get_total_stimulation() -> float:
	var total: float = 0.0
	for val: float in _stimulation.values():
		total += val
	return total


## Get the most stimulated body part name.
func get_most_stimulated_part() -> String:
	var best_name: String = ""
	var best_val: float = 0.0
	for part_name: String in _stimulation.keys():
		var val: float = _stimulation[part_name] as float
		if val > best_val:
			best_val = val
			best_name = part_name
	return best_name


# ── Internal ─────────────────────────────────────────────────────────────────

## Returns a multiplier based on how the touch type interacts with the zone.
func _get_touch_multiplier(touch_type: TouchType, zone: NerveSensitivity.Zone) -> float:
	# Base multipliers per touch type
	var base: float = 1.0
	match touch_type:
		TouchType.GRAB:
			base = 0.8
		TouchType.RELEASE:
			base = 0.2
		TouchType.PUSH:
			base = 1.5
		TouchType.PUSH_RELEASE:
			base = 1.8
		TouchType.STROKE:
			base = 0.5
		TouchType.PULL:
			base = 1.2
		TouchType.PRESS:
			base = 0.6
		TouchType.IMPACT:
			# Velocity-based collisions — raw intensity already carries the speed
			base = 1.0
		TouchType.LICK:
			base = 0.4  # Light but persistent — pleasure accumulates
		TouchType.SUCK:
			base = 0.7  # Rhythmic negative pressure — moderate intensity
		TouchType.BITE:
			base = 1.6  # Sharp pressure — high intensity, pain-prone

	# Zone modifiers
	match zone:
		NerveSensitivity.Zone.EROGENOUS:
			if touch_type == TouchType.STROKE:
				base *= 2.0
			elif touch_type == TouchType.GRAB:
				base *= 1.3
		NerveSensitivity.Zone.PAIN_PRONE:
			if touch_type == TouchType.PUSH or touch_type == TouchType.PUSH_RELEASE:
				base *= 1.5
			elif touch_type == TouchType.IMPACT:
				base *= 1.8  # Impacts hurt more on pain-prone zones
		NerveSensitivity.Zone.TICKLISH:
			if touch_type == TouchType.STROKE:
				base *= 1.8
			elif touch_type == TouchType.LICK:
				base *= 2.2  # Licking a ticklish zone is very effective
		NerveSensitivity.Zone.PRESSURE_POINT:
			if touch_type == TouchType.IMPACT:
				base *= 1.4  # Pressure points amplify impact force
			elif touch_type == TouchType.BITE:
				base *= 1.5  # Biting a pressure point — intense

	# Mouth-specific zone interactions
	if touch_type == TouchType.LICK and zone == NerveSensitivity.Zone.EROGENOUS:
		base *= 2.0  # Tongue on erogenous zone — high pleasure multiplier
	elif touch_type == TouchType.SUCK and zone == NerveSensitivity.Zone.EROGENOUS:
		base *= 1.8  # Suction on erogenous zone
	elif touch_type == TouchType.BITE and zone == NerveSensitivity.Zone.PAIN_PRONE:
		base *= 1.6  # Biting pain-prone tissue

	return base
